#!/usr/bin/env python3
"""Generate the Docsify shell for the Markdown documentation."""

from __future__ import annotations

import argparse
import difflib
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"

LOGO_LIGHT = "https://github.com/user-attachments/assets/a5d8303a-4519-4af8-853d-fab9667387aa"


@dataclass(frozen=True)
class DocPage:
    title: str
    path: str
    description: str


DOC_PAGES = [
    DocPage("Home", "index.md", "Documentation map and current scope."),
    DocPage("Installation", "installation.md", "Setup, builds, diagnostics, and compatibility."),
    DocPage("Quickstart", "quickstart.md", "First tree, query, raycast, and render workflow."),
    DocPage("Python API", "python-api.md", "Python objects, NumPy paths, and CUDA/Torch paths."),
    DocPage("C++ API", "cpp-api.md", "Public C++ headers, examples, and CMake usage."),
    DocPage("PyTorch Rendering", "pytorch-rendering.md", "CUDA tensor interop, VolumeRenderer, and autograd."),
    DocPage("Architecture", "architecture.md", "Layering, ownership, repository layout, and design rules."),
    DocPage("Data Layout", "data-layout.md", "Node descriptors, branching modes, and payload indirection."),
    DocPage("File Format", "file-format.md", "Saved .svo scenes, payload arrays, and benchmark loading."),
    DocPage("Differentiability", "differentiability.md", "Gradient scope and discrete topology limits."),
    DocPage("Performance Roadmap", "performance-roadmap.md", "Benchmark scenes, metrics, and acceleration decisions."),
    DocPage("Testing", "testing.md", "Local tests, CUDA tests, numerical rules, and CI expectations."),
    DocPage("Packaging", "packaging.md", "Runtime wheels, source distributions, and release flow."),
    DocPage("Troubleshooting", "troubleshooting.md", "Common install, CUDA, Torch, and input issues."),
    DocPage("Examples", "examples.md", "Runnable examples and planned examples."),
    DocPage("Documentation Workflow", "documentation.md", "How to update, preview, and publish docs."),
]


INDEX_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Sparse Voxel Octree CUDA Documentation</title>
  <meta name="description" content="Sparse Voxel Octree CUDA documentation">
  <link rel="icon" href="data:,">
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css">
  <style>
    :root {
      --theme-color: #2563eb;
    }

    .cover-main img {
      max-width: min(520px, 82vw);
    }

    .cover.show {
      background:
        radial-gradient(circle at 20% 20%, rgba(186, 230, 253, 0.82), transparent 34%),
        radial-gradient(circle at 78% 28%, rgba(167, 243, 208, 0.78), transparent 32%),
        linear-gradient(135deg, #eff6ff 0%, #ccfbf1 48%, #e0f2fe 100%) !important;
    }

    .markdown-section {
      max-width: 980px;
    }

    .markdown-section table {
      display: table;
      width: 100%;
    }
  </style>
</head>
<body>
  <div id="app">Loading documentation...</div>
  <script>
    window.$docsify = {
      name: 'Sparse Voxel Octree CUDA',
      repo: 'hectorpiteau/sparse-voxels',
      homepage: 'index.md',
      coverpage: true,
      loadSidebar: true,
      subMaxLevel: 2,
      auto2top: true,
      search: {
        placeholder: 'Search',
        noData: 'No results',
        depth: 3
      }
    };
  </script>
  <script src="//cdn.jsdelivr.net/npm/docsify@4/lib/docsify.min.js"></script>
  <script src="//cdn.jsdelivr.net/npm/docsify@4/lib/plugins/search.min.js"></script>
</body>
</html>
"""


def generated_header(source: str) -> str:
    return f"<!-- Generated by {source}; edit scripts/generate_docsify.py instead. -->\n\n"


def render_sidebar() -> str:
    lines = [generated_header("scripts/generate_docsify.py"), "* Documentation"]
    lines.extend(f"  * [{page.title}]({page.path})" for page in DOC_PAGES)
    lines.append("")
    return "\n".join(lines)


def render_coverpage() -> str:
    return (
        generated_header("scripts/generate_docsify.py")
        + f"![Sparse Voxel Octree CUDA logo]({LOGO_LIGHT})\n\n"
        + "# Sparse Voxel Octree CUDA\n\n"
        + "> C++20/CUDA sparse voxel octree library with pybind11 Python bindings, "
        + "NumPy CPU APIs, CUDA traversal/rendering, and optional PyTorch CUDA autograd integration.\n\n"
        + "[GitHub](https://github.com/hectorpiteau/sparse-voxels)\n"
        + "[Get Started](quickstart.md)\n"
        + "[Installation](installation.md)\n"
    )


def render_documentation_workflow() -> str:
    pages = "\n".join(f"- [{page.title}]({page.path}): {page.description}" for page in DOC_PAGES)
    return f"""# Documentation Workflow

The documentation source lives in `docs/` as normal Markdown files. The Docsify
site shell is generated from `scripts/generate_docsify.py` so navigation stays
consistent and easy to review.

## Edit Documentation

1. Edit the relevant Markdown file in `docs/`.
2. If you add, rename, or remove a page, update `DOC_PAGES` in
   `scripts/generate_docsify.py`.
3. Regenerate the Docsify shell:

```bash
./.venv/bin/python scripts/generate_docsify.py
```

4. Check that generated files are current:

```bash
./.venv/bin/python scripts/generate_docsify.py --check
```

## Preview Locally

Docsify does not need a build step for normal preview. It serves Markdown files
directly in the browser:

```bash
npx docsify-cli serve docs
```

Then open the local URL printed by Docsify, usually `http://localhost:3000`.

If Node is not available, the Markdown files still render directly on GitHub.

## Publish Online

The GitHub Pages workflow in `.github/workflows/docs.yml` publishes the `docs/`
directory. Repository settings must allow Pages deployments from GitHub Actions.

Generated Docsify files that should be committed:

- `docs/index.html`
- `docs/_sidebar.md`
- `docs/_coverpage.md`
- `docs/.nojekyll`

Temporary static export folders are ignored by `.gitignore`.

## Current Pages

{pages}
"""


def expected_files() -> dict[Path, str]:
    return {
        DOCS_DIR / "index.html": INDEX_HTML,
        DOCS_DIR / "_sidebar.md": render_sidebar(),
        DOCS_DIR / "_coverpage.md": render_coverpage(),
        DOCS_DIR / ".nojekyll": "",
        DOCS_DIR / "documentation.md": render_documentation_workflow(),
    }


def check_files(files: dict[Path, str]) -> int:
    failed = False
    for path, expected in files.items():
        actual = path.read_text(encoding="utf-8") if path.exists() else ""
        if actual == expected:
            continue
        failed = True
        print(f"{path.relative_to(REPO_ROOT)} is not up to date", file=sys.stderr)
        diff = difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"{path.relative_to(REPO_ROOT)} (current)",
            tofile=f"{path.relative_to(REPO_ROOT)} (expected)",
        )
        sys.stderr.writelines(diff)
    return 1 if failed else 0


def write_files(files: dict[Path, str]) -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    for path, content in files.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated Docsify files are not up to date")
    args = parser.parse_args()

    files = expected_files()
    if args.check:
        return check_files(files)
    write_files(files)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
